# Generated by Django 4.0.3 on 2022-07-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='flaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
